### ISSUE TITLE
Allow hiding the tag list for documents

### ISSUE THREAD

**Issue by r0ckarong** [dokufreaks/plugin-tag#107]
I'm exporting a lot of my tagged pages into PDF and HTML documents that are used outside of the wiki context. My problem is that the list of tags is always rendered in the output files. This leads to confusion for the user and frankly looks bad. 

Is there a way to hide the tag list from being displayed in print/export? I want to preserve the tag listing functionality for the Wiki but want to omit it when pushing a document out. Ideally the tag argument would itself take a flag that avoids printing the taglist in output.

e.g.

```
{{tag>tag1 tag2&noprint}}}
```

Alternatively I'd love to get some suggestions how I can manually "crop" the tag list out of things like dw2pdf and export_html.

**Comment by Klap-in** [comment]
If you do `?do=export_html` then the whole page is wrapped in `<div class="dokuwiki export">...</div>` elements. That might be useful for specific layouting.

dw2pdf plugin respects `print.css`, if you like to have more specific layouting for the pdf, you can use `pdf.css` in the tag plugin folder as well. Or if you have created an own pdf-template for dw2pdf's pdf exports, you can add such css also to the css of that pdf-template.

To improve performance there is some caching happening at different places. Normally, resaving the Configuration Manager is enough. Subsequential, sometimes you can speed up refreshing of the browser's cache by `Ctrl+F5`.
