### ISSUE TITLE
List where contain all tags

### ISSUE THREAD

**Issue by thorst** [dokufreaks/plugin-tag#120]
{{tagpage>Cat Male|Male Cats}}

Currently this will display all cats and all males. So male dogs will be there, and female cats will be there was well.

Its would be nice to allow users to say, only list articles where they contain all the listed tags

**Comment by michitux** [comment]
Does the [topic](https://www.dokuwiki.org/plugin:tag#topic) syntax already do what you want? Your request sounds very similar except that the tag pages are separate pages and not displayed inline.
