### ISSUE TITLE
Helper plugin pagelist is not available or invalid.

### ISSUE THREAD

**Issue by mrminus** [dokufreaks/plugin-tag#126]
i'm new to dokuwiki and "tag". i can tag pages pretty successfully, but when i click on the tag i get the error in the title:

Helper plugin pagelist is not available or invalid.

What should I be looking at to fix this?

**Comment by linuxturtle** [comment]
You need to install the "pagelist" plugin as well.  It's listed as a dependency of the "tag" plugin.
