### ISSUE TITLE
reverse sorting

### ISSUE THREAD

**Issue by TechLifeWeb** [dokufreaks/plugin-tag#142]
In the admin panel, I have my tags sorted by title. I can change a setting in the admin panel and this code will sort ascending or decending based on that global setting.
<code>
{{topic>watching -done&nouser&nodate&notags}}
</code>

However, adding the **rsort** flag doesn't work to change the sort direction on an a particular set of tags.

**Comment by LarsGit223** [comment]
This should be fixed now, please check.
Regards, Lars

**Comment by TechLifeWeb** [comment]
Works as expected now.
Thanks for the quick response.
