### ISSUE TITLE
PHP 7.0 compliance

### ISSUE THREAD

**Issue by turnermm** [dokufreaks/plugin-tag#154]
Declaration of action_plugin_tag::register(&$contr) should be compatible with DokuWiki_Action_Plugin::register(Doku_Event_Handler $controller)

**Comment by MOEditor** [comment]
I'm also receiving several warnings regarding PHP compatibility. Below are a list of warnings I received after installing the plugin. I really hope this is fixed soon :( I'm very, very excited about this plugin and its support with the bootstrap 3 theme.

  * Warning: Declaration of action_plugin_tag::register(&$contr) should be compatible with DokuWiki_Action_Plugin::register(Doku_Event_Handler $controller) in C:\xampp\htdocs\dokuwiki\lib\plugins\tag\action.php on line **141**

  * Warning: Declaration of syntax_plugin_tag_count::handle($match, $state, $pos, &$handler) should be compatible with DokuWiki_Syntax_Plugin::handle($match, $state, $pos, Doku_Handler $handler) in C:\xampp\htdocs\dokuwiki\lib\plugins\tag\syntax\count.php on line **130**

  * Warning: Declaration of syntax_plugin_tag_count::render($mode, &$renderer, $data) should be compatible with DokuWiki_Syntax_Plugin::render($format, Doku_Renderer $renderer, $data) in C:\xampp\htdocs\dokuwiki\lib\plugins\tag\syntax\count.php on line **130**

  * Warning: Declaration of syntax_plugin_tag_searchtags::handle($match, $state, $pos, &$handler) should be compatible with DokuWiki_Syntax_Plugin::handle($match, $state, $pos, Doku_Handler $handler) in C:\xampp\htdocs\dokuwiki\lib\plugins\tag\syntax\searchtags.php on line **278**

  * Warning: Declaration of syntax_plugin_tag_searchtags::render($mode, &$renderer, $data) should be compatible with DokuWiki_Syntax_Plugin::render($format, Doku_Renderer $renderer, $data) in C:\xampp\htdocs\dokuwiki\lib\plugins\tag\syntax\searchtags.php on line **278**

  * Warning: Declaration of syntax_plugin_tag_tag::handle($match, $state, $pos, &$handler) should be compatible with DokuWiki_Syntax_Plugin::handle($match, $state, $pos, Doku_Handler $handler) in C:\xampp\htdocs\dokuwiki\lib\plugins\tag\syntax\tag.php on line **118**

  * Warning: Declaration of syntax_plugin_tag_tag::render($mode, &$renderer, $data) should be compatible with DokuWiki_Syntax_Plugin::render($format, Doku_Renderer $renderer, $data) in C:\xampp\htdocs\dokuwiki\lib\plugins\tag\syntax\tag.php on line **118**

  * Warning: Declaration of syntax_plugin_tag_tagpage::handle($match, $state, $pos, &$handler) should be compatible with DokuWiki_Syntax_Plugin::handle($match, $state, $pos, Doku_Handler $handler) in C:\xampp\htdocs\dokuwiki\lib\plugins\tag\syntax\tagpage.php on line **96**

  * Warning: Declaration of syntax_plugin_tag_tagpage::render($mode, &$renderer, $data) should be compatible with DokuWiki_Syntax_Plugin::render($format, Doku_Renderer $renderer, $data) in C:\xampp\htdocs\dokuwiki\lib\plugins\tag\syntax\tagpage.php on line **96**

  * Warning: Declaration of syntax_plugin_tag_topic::handle($match, $state, $pos, &$handler) should be compatible with DokuWiki_Syntax_Plugin::handle($match, $state, $pos, Doku_Handler $handler) in C:\xampp\htdocs\dokuwiki\lib\plugins\tag\syntax\topic.php on line **133**

  * Warning: Declaration of syntax_plugin_tag_topic::render($mode, &$renderer, $data) should be compatible with DokuWiki_Syntax_Plugin::render($format, Doku_Renderer $renderer, $data) in C:\xampp\htdocs\dokuwiki\lib\plugins\tag\syntax\topic.php on line **133**

**Comment by michitux** [comment]
I've just fixed all these issues in f6f51477b809df0672cc5f55b85bbf0e5a338754 and released a new version, please update the plugin.
