### ISSUE TITLE
PHP7 deprecated constructor

### ISSUE THREAD

**Issue by ssahara** [dokufreaks/plugin-tag#179]
PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; helper_plugin_tag has a deprecated constructor in [line 17 of helper.php](https://github.com/dokufreaks/plugin-tag/blob/master/helper.php#L17).

Change function name from `helper_plugin_tag()` to `__construct()` will solve this issue.

**Comment by LarsGit223** [comment]
Done.
