### ISSUE TITLE
Javascript placement

### ISSUE THREAD

**Issue by MattLarsonAMS** [dokufreaks/plugin-tag#188]
Greetings.  On the documentation page for the plugin, you have some example Javascript to change the background of the page based on a tag.  There is, alas, no mention of *where* the Javascript should go.

**Comment by Klap-in** [comment]
DokuWiki reads javascript files from the plugin directory (if placed and/or referered at the right place), or from the global configuration directory.
Please see https://www.dokuwiki.org/devel:javascript
