### ISSUE TITLE
Diff Icon

### ISSUE THREAD

**Issue by BMCSamael** [dokufreaks/plugin-tag#193]
Stage to set.  
This is a nested installation.  The root domain XXX.YYY.COM hosts our ticket system.  XXX.YYY.COM/dokuwiki hosts our wiki as such the lib file path ONLY in this plugin is not being handled.  The remainder of the site properly attaches to the BASE URL and BASE DIR properly that is autodetected.  I tried manually as well no go for this plugin.

When rendering the tag list the diff icon is not showing and is broken.  It is referencing /lib/images/fileicons/diff.png

USE Case:  {{topic>meeting:video&desc&notags&nouser&nodate&firsthl&header}}

![bug](https://user-images.githubusercontent.com/1844256/41268812-e9b69d9a-6dcf-11e8-8e8a-2374def6ef7e.png)

****

**Comment by Klap-in** [comment]
Which webserver do you use?

**Comment by BMCSamael** [comment]
apache
