### ISSUE TITLE
Tag breaks between icon and label

### ISSUE THREAD

**Issue by suedunham** [dokufreaks/plugin-tag#217]
When I have so large number of tags on a page that a second line is needed to display them, the line break comes in one tag between its icon and the label, as pictured. This is in Hogfather with the newest versions of everything, new chrome.

![tagbreak](https://user-images.githubusercontent.com/42522840/100089078-1c624c00-2e1f-11eb-910f-63eeed1f363f.jpg)

**Comment by lpaulsen93** [comment]
This might be template specific. What template are you using?

**Comment by suedunham** [comment]
I'm using the Bootstrap3 template.

**Comment by Rainbow-Spike** [comment]
Try <div ... nowrap> attribute
