### ISSUE TITLE
httpd core-dump error when plugin enabled on Igor/PHP 8

### ISSUE THREAD

**Issue by mprins** [dokufreaks/plugin-tag#224]
When the plugin is enabled in a master/Igor running on PHP 8.0.13 the ~~Apache~~ uWSGI process dies (nothing is logged in the httpd error log, nothing is logged in the DW error log, just a 500 error page is sent.

This is on a hosted environment with upgraded wiki so not possible to explore further, I'll set up a local environment to see if I can get anything useful...

**Comment by mprins** [comment]
Well that's annoying... cannot reproduce locally (PHP 8.0.8) with Apache2

**Comment by splitbrain** [comment]
a php script should not be able to crash the php interpreter. whenever it does, it is a bug in (that particular) php.

**Comment by mprins** [comment]
After upgrading to latest `master` (again) today I can no longer reproduce. I must have overseen something.
