### ISSUE TITLE
Disappearing tags

### ISSUE THREAD

**Issue by AwesomeTeo** [dokufreaks/plugin-tag#229]
After update to v. 2022-06-17  my tags starts to disappearing from pages. Literally with each refresh number of pages in topic is lowering.  On random pages tags did not listed, only in code.  
Release 2020-07-29 "Hogfather"
PHP 7.4 bx-optimized

**Comment by Klap-in** [comment]
Please give some examples of syntax which can be used for testing.

**Comment by Klap-in** [comment]
@AwesomeTeo Do you have any examples, otherwise there is not enough information to keep this open.
