### ISSUE TITLE
Tag plugin error with new DW version Igor (reason: &sort / &rsort option) 

### ISSUE THREAD

**Issue by glreschke** [dokufreaks/plugin-tag#230]
[Obviously identical with "PHP8: Error: Call to undefined function create_function() #225"]

A red message is shown:

> Error: Call to undefined function create_function()
An unforeseen error has occured. This is most likely a bug somewhere. It might be a problem in the tag plugin.
More info has been written to the DokuWiki error log.

The log is:

> Error: Call to undefined function create_function()
/home/phoenixs/www/sinnperspektive/wiki/lib/plugins/tag/syntax/topic.php(106)
#0 /home/phoenixs/www/sinnperspektive/wiki/inc/parser/renderer.php(117): syntax_plugin_tag_topic->render('xhtml', Object(Doku_Renderer_xhtml), Array)
#1 /home/phoenixs/www/sinnperspektive/wiki/inc/parserutils.php(682): Doku_Renderer->plugin('tag_topic', Array, 5, '{{topic>marco?t...')
#2 /home/phoenixs/www/sinnperspektive/wiki/inc/parserutils.php(149): p_render('xhtml', Array, NULL)
#3 /home/phoenixs/www/sinnperspektive/wiki/inc/parserutils.php(89): p_cached_output('/home/phoenixs/...', 'xhtml', '2:marco')
#4 /home/phoenixs/www/sinnperspektive/wiki/inc/Ui/PageView.php(68): p_wiki_xhtml('2:marco', 0, true, '')
#5 /home/phoenixs/www/sinnperspektive/wiki/inc/Action/Show.php(37): dokuwiki\Ui\PageView->show()
#6 /home/phoenixs/www/sinnperspektive/wiki/inc/template.php(100): dokuwiki\Action\Show->tplContent()
#7 [internal function]: tpl_content_core('show')
#8 /home/phoenixs/www/sinnperspektive/wiki/inc/Extension/Event.php(133): call_user_func_array('tpl_content_cor...', Array)
#9 /home/phoenixs/www/sinnperspektive/wiki/inc/Extension/Event.php(199): dokuwiki\Extension\Event->trigger('tpl_content_cor...', true)
#10 /home/phoenixs/www/sinnperspektive/wiki/inc/template.php(85): dokuwiki\Extension\Event::createAndTrigger('TPL_ACT_RENDER', 'show', 'tpl_content_cor...')
#11 /home/phoenixs/www/sinnperspektive/wiki/lib/tpl/dokuwiki/main.php(59): tpl_content()
#12 /home/phoenixs/www/sinnperspektive/wiki/inc/actions.php(27): include('/home/phoenixs/...')
#13 /home/phoenixs/www/sinnperspektive/wiki/doku.php(126): act_dispatch()
#14 {main}

The cause is the option **&rsort** in **{{topic>...**
If it is removed, everything works well.
**&sort** also raises the error.

PHP 8.0, command:
{{topic>marco?blog&nodate&nouser&rsort}}

Config options are:

> Standard-Namensraum für Tags > tag
Themenlisten sortieren nach > Titel
Sortierrichtung > aufsteigend
Formatieroptionen für die Tagliste > list
Standardaussehen

**Comment by Klap-in** [comment]
I made some changes. Could you try already by reinstall the plugin in the Extension manager? Does it work fine for you?

**Comment by glreschke** [comment]
Yes, it is working now. Thank you very much for the fast support!
