### ISSUE TITLE
Tags cause page not rendered

### ISSUE THREAD

**Issue by londoss** [dokufreaks/plugin-tag#232]
Hi,

last update cause that pages with tags are not rendered, only blank page with sidebar is shown.
Reinstall not helped only disable.

Release 2018-04-22c "Greebo"
Template v2021-03-11 (stable/20210311)

**Comment by Klap-in** [comment]
Please check the logs for the error messages and share them here. Thanks.

Please share also an (example of) the syntax used at that page. Such that we can reproduce your situation.
Which version of PHP are you using? (Add ?do=check or &do=check to the url for more info)

**Comment by londoss** [comment]
> Please check the logs for the error messages and share them here. Thanks.
> 
> Please share also an (example of) the syntax used at that page. Such that we can reproduce your situation. Which version of PHP are you using? (Add ?do=check or &do=check to the url for more info)

Hi, 

thanks for quick reply. I do not have any logging plugin 

Example page with code https://archi.gov.cz/znalostni_baze:funkcni_celek 

DO CHECK plugin disabled

DokuWiki version: Release 2018-04-22c "Greebo"
PHP version 7.4.3
More than 32MB RAM (134217728 bytes) available.
Changelog is writable
conf directory is writable
mb_string extension is available and will be used
Your locale C seems not to be a UTF-8 locale, you should fix this if you encounter problems.
Debugging support is disabled
You are currently logged in as XXX
You are part of the groups admin, user
Your current permission for this page is 255
The current page is writable by the webserver
The current page is writable by you
The search index seems to be working
Server time seems to be okay. Diff: 0s
Template version v2021-03-11 (stable/20210311)

DO CHECK plugin enabled

DokuWiki version: Release 2018-04-22c "Greebo"
PHP version 7.4.3
More than 32MB RAM (134217728 bytes) available.
Changelog is writable
conf directory is writable
mb_string extension is available and will be used
Your locale C seems not to be a UTF-8 locale, you should fix this if you encounter problems.
Debugging support is disabled
You are currently logged in as XXX
You are part of the groups admin, user
Your current permission for this page is 255
The current page is writable by the webserver
The current page is writable by you
The search index seems to be working
Server time seems to be okay. Diff: 1s
Template version v2021-03-11 (stable/20210311)

**Comment by Klap-in** [comment]
Here a pointer for how to locate the server logs. https://www.dokuwiki.org/faq:blankpage could you find error messages?

**Comment by londoss** [comment]
Hi,

thanks for advice. I do not have Igor version since I need to test if upgrade is possible. But I have found some errors in NGINX error log 

2022/07/25 12:17:08 [error] 389411#389411: *248754 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Class 'dokuwiki\Extension\Event' not found in /opt/dokuwiki/lib/plugins/tag/helper.php:156
Stack trace:
#0 /opt/dokuwiki/lib/plugins/tag/helper.php(110): helper_plugin_tag->tagLink()
#1 /opt/dokuwiki/lib/plugins/tag/syntax/tag.php(78): helper_plugin_tag->tagLinks()
#2 /opt/dokuwiki/inc/parser/renderer.php(111): syntax_plugin_tag_tag->render()
#3 /opt/dokuwiki/inc/parserutils.php(654): Doku_Renderer->plugin()
#4 /opt/dokuwiki/inc/parserutils.php(130): p_render()
#5 /opt/dokuwiki/inc/parserutils.php(83): p_cached_output()
#6 /opt/dokuwiki/inc/html.php(293): p_wiki_xhtml()
#7 /opt/dokuwiki/inc/Action/Show.php(33): html_show()
#8 /opt/dokuwiki/inc/template.php(98): dokuwiki\Action\Show->tplContent()
#9 /opt/dokuwiki/inc/events.php(111): tpl_content_core()
#10 /opt/dokuwiki/inc/events.php(256): Doku_Event->trigger()
#11 /opt/dokuwiki/inc/template.php(83): trigger_event()
#12 /opt/dokuwiki/lib/tpl/bootstrap3/main.php(117): tpl_content()
#13 /opt/dokuwiki/in" while reading upstream, client: 10.32.0.1, server: archi.gov.cz, request: "GET /nap:portaly_verejne_spravy_a_soukromopravnich_uzivatelu_udaju?rev=1645527720 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.4-fpm.sock:", host: "archi.gov.cz"

2022/07/25 00:05:09 [error] 389410#389410: *216683 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Class 'dokuwiki\Extension\Event' not found in /opt/dokuwiki/lib/plugins/tag/helper.php:156
Stack trace:
#0 /opt/dokuwiki/lib/plugins/tag/helper.php(110): helper_plugin_tag->tagLink()
#1 /opt/dokuwiki/lib/plugins/tag/helper.php(197): helper_plugin_tag->tagLinks()
#2 /opt/dokuwiki/lib/plugins/tag/action.php(81): helper_plugin_tag->getTopic()
#3 /opt/dokuwiki/inc/events.php(229): action_plugin_tag->_handle_tpl_act()
#4 /opt/dokuwiki/inc/events.php(70): Doku_Event_Handler->process_event()
#5 /opt/dokuwiki/inc/Action/Plugin.php(27): Doku_Event->advise_before()
#6 /opt/dokuwiki/inc/template.php(98): dokuwiki\Action\Plugin->tplContent()
#7 /opt/dokuwiki/inc/events.php(111): tpl_content_core()
#8 /opt/dokuwiki/inc/events.php(256): Doku_Event->trigger()
#9 /opt/dokuwiki/inc/template.php(83): trigger_event()
#10 /opt/dokuwiki/lib/tpl/bootstrap3/main.php(117): tpl_content()
#11 /opt/dokuwiki/inc/actions.php(27): include('/opt/dokuwiki/l...')
#12 /opt/dokuwiki/do" while reading upstream, client: 10.32.0.1, server: archi.gov.cz, request: "GET /tag:ztotozneni?do=showtag&tag=ztoto%C5%BEn%C4%9Bn%C3%AD HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7.4-fpm.sock:", host: "archi.gov.cz"

Is it sufficient?

**Comment by splitbrain** [comment]
Release 2018-04-22c "Greebo" is ancient. Upgrade!
