### ISSUE TITLE
Tags no longer working

### ISSUE THREAD

**Issue by aod-john-github** [dokufreaks/plugin-tag#237]
Tags worked fine on pages until I started using the Bootstrap Wrapper Plugin with the Bootstrap3 template. Any assistance you can provide to get the tags working again would be great. Thanks

**Comment by michitux** [comment]
What exactly is broken/not working? What exact syntax are you using on the page where the tag plugin isn't working as expected?

**Comment by aod-john-github** [comment]
The list of tags do not show on any page now. I'm using the simplest of the examples in the documentation:
{{tag>[list of tags]}}

i.e. {{tag>[bray world universe sigma]}}
Everything works as expected on wiki installs without a aforementioned Bootstrap Wrapper Plugin with the Bootstrap3 template installed.

I even uninstalled/reinstalled the plugin (as well as pagelist plugin) after I installed the Bootstrap stuff.

I also installed the searchindex plugin and rebuilt the indexes after reinstalling tag and pagelist plugins. Tags still do not show on any page

Thanks for your time :-)

**Comment by Klap-in** [comment]
With a bit testing, I guess that the different positioning of the tags is probably confusing?
The 'dokuwiki' template (and other templates) will show the tags at the place in where you typed them. The bootstrap3 template collects all tags at the top right of the page, yet above the page tools, next to the page name.

**Comment by Klap-in** [comment]
Was the different positioning the problem here? Therefore, this issue can be closed?
