### ISSUE TITLE
PHP8.1 Warnings

### ISSUE THREAD

**Issue by LMS235** [dokufreaks/plugin-tag#239]
Warnings with PHP8.1

`PHP Warning:  Trying to access array offset on value of type null in .../lib/plugins/tag/helper.php on line 427
`

**Comment by Klap-in** [comment]
Could you reinstall the tag plugin in the Extension Manager, and test if it is solved?

**Comment by LMS235** [comment]
Error solved with the actual https://github.com/dokufreaks/plugin-tag/archive/refs/heads/master.zip

**Comment by LMS235** [comment]
But now:

Error: Cannot access protected property helper_plugin_tag::$namespace

![image](https://user-images.githubusercontent.com/8693550/193405254-2e5bd779-ccce-46f3-92fe-b3213126166e.png)

**Comment by LMS235** [comment]
somethin with the fix is wrong. after restore the old version it works again (with the warnings)

**Comment by Klap-in** [comment]
Could you please provide the entire error message from the log file?

**Comment by Klap-in** [comment]
Which (tag related) plugins do you use? I guess some other plugins depends on the namespace property..

**Comment by LMS235** [comment]
Cloud Plugin (for 15 TOP Tags)

**Comment by Klap-in** [comment]
i found these uses, temporary fix is making 'namespace' temporary public
https://codesearch.dokuwiki.org/xref/plugin/cumulus/syntax.php#141
https://codesearch.dokuwiki.org/xref/plugin/ckgedit/action/tagapi.php#64
https://codesearch.dokuwiki.org/xref/plugin/cloud/syntax.php#114
