### ISSUE TITLE
version mismatch

### ISSUE THREAD

**Issue by arlt** [dokufreaks/plugin-tag#242]
- https://www.dokuwiki.org/plugin:tag: `Last updated on
    2022-09-30` (by Klap-in)
- https://github.com/dokufreaks/plugin-tag/blob/master/plugin.info.txt#L4: `date   2022-10-02` (by splitbrain) 
- Dokuwiki instance says: `Update: Version 2022-09-30 steht zum Download bereit.`

**Comment by Klap-in** [comment]
Fixed, thanks.
