### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by Sonn117** [dokufreaks/plugin-tag#243]
Plugin is not working, Dokuwiki Admin page is displaying blank content.
/var/log/apache2/errors.log shows this error 
`Got error 'PHP message: PHP Parse error:  syntax error, unexpected '=' in /home/wiki/public/lib/plugins/tag/syntax/count.php on line 48\n'`

**Comment by Klap-in** [comment]
Which php version are you using?
```php
[$tags, $nsstring] = array_pad(explode('&', $match,2),2,'');  // split to tags and allowed namespaces
```
Could you try the following on line 48 of syntax/count.php?
```php
list($tags, $nsstring) = array_pad(explode('&', $match,2),2,''); // split to tags and allowed namespaces
```
This language construct works from php 7.1..

**Comment by runout-at** [comment]
The latest commit of the tag plugin breaks dokuwiki Release 2020-07-29 "Hogfather" and PHP7.0 for me.

The issue is:

    PHP Parse error: syntax error, unexpected '=' in /.../tag/syntax/count.php on line 48

`list($tags, $nsstring) = array_pad(` ... does not work either. maybe array_pad is not really suited for this.

**Comment by Klap-in** [comment]
The syntax used here is supported by PHP 7.1 and newer. Unfortunately, it is not workable to support older versions.
