### ISSUE TITLE
Tag plugin seems broken in Rincewind-2011_05-25a

### ISSUE THREAD

**Issue by phidele** [dokufreaks/plugin-tag#43]
topic.idx file is becoming corrupted as soon as a file is edited or wiki  is updating its cache.

**Two obvious bugs in the topic.idx :**
- creation of additionnal tags with a "+" in front of an already existing name of tag
- creation of  wrong additionnal keys between one or more already  existing tag and one or more already existing page

Corruption of the topic.idx file is having also a lot of bad side effects I will not list here.
The rebuilt of the topic.idx by Tagindex  manager is fixing the issue but the corruption restart just after :-((
Having also purge all the cache, index and revisions plus rebuilt all tags from scratch... But don't fix anything.

**Plugin is used with the following list of plugins installed:**
- cacherevisionserase - clearfloat - cloud - columns - comment - dir - fontcolor - fontsize2 - goto - hilited
- iframe - imagebox - imagemap - infomail - navi - note - nspages - odt - pagelist - searchindex - styler
  - swiftmail - uparrow - usersubscriptions - wrap

Thank you for help and advices

**Comment by Klap-in** [comment]
Probably fixed.
