### ISSUE TITLE
I'm having similar problems with rincewind

### ISSUE THREAD

**Issue by robmacl** [dokufreaks/plugin-tag#50]
I'm getting bad use counts for the tags, which is affecting the tagcloud.  These bad counts are visible using {{count>+}}.  It seems that the counts just keep going up.  I'm using the version of tag downloaded from dokuwiki.org on 4-sep-11.  If I rebuild the tagindex then the counts are reinitialized to sane values.  However, I am _NOT_ seeing the problem of bad entries in the {{topic> }} display.

**Comment by Klap-in** [comment]
No further feedback, let's assume it works fine now.
