### ISSUE TITLE
Update tags on a page doesn't clear taglist

### ISSUE THREAD

**Issue by lvg** [dokufreaks/plugin-tag#52]
LS,

When a page is edited and one of the given tags was changed, the changed tag is added to the taglist but de old tag isn't cleared.

For example a page with following tags:

original: {{tag>tag1 tag2}}
changed: {{tag> tag1 tag3}}

comes up after the change in:

{{topic>tag1 +tag3}} and {{topic>tag1 +tag2}}

The last isn't expected off course!

Kind regards, Luitzen

**Comment by Klap-in** [comment]
Works for me.
