### ISSUE TITLE
Wishlist: Automatic List of all Tags = Keyword Index 

### ISSUE THREAD

**Issue by hemmerling** [dokufreaks/plugin-tag#6]
Hello,
the final wish is a generator for an automatic taglist, a "keyword index"
which collects all tags found in given namespace, a list of namespaces or "all" pages of a dokuwiki site, with a display

example
((taglist>:)) or ((taglist>)) lists all tags

((taglist>namespace1))

((taglist>namespace1, namespace2))

list output should be
-name-of-the-tag1

  -h1-tag-of-the-page1-where-it-appears

  -h1-tag-of-the-page2-where-it-appears

  -h1-tag-of-the-page3-where-it-appears

-name-of-the-tag2

  -h1-tag-of-the-page1-where-it-appears

  -h1-tag-of-the-page2-where-it-appears

  -h1-tag-of-the-page3-where-it-appears

as known from the topic command.

There should be an **optional** alphabetic order sort option.

The plugin function should NOT be limited to "little" websites, but should somehow be able to handle many tags with LITTLE internal PHP memory ( which is limited to 32K or 64K very often)

a)
The alphabetic order sort option must be optional = can be switched off, for PHP accounts with too little memory for a given number of tags and pages.

b)
Alternative syntax, to distribute such keyword indexes to several pages ( even the length of a Dokuwiki pages is very-very limited, due to lack of PHP memory, e.g. the limits of 32k or 64k PHP memory ).

((taglist>a-z, namespace1)) = lists all tags which start with a-z, for namespace1

((taglist>a b c d, namespace1)) = lists all tags which start with a,b,c,d, for namespace1

To preserve compatibilty, this should be considered during design.

c)
I don´t know how to do this:
Alternatively to the display by a command, there should be an option to get the list as text ( output to a textfile ), so that it can be sorted an manipulated by hand, and inserted manually on a page.

Well remember a 1000 pages dokuwiki with 10.000 tags, 
due to lack of memory, you can´t even use the suggested "taglist" function, 
nor do the generated list of tags fit on one page, due to lack of memory too.

The result would be something like a "keyword index" ( currently I prepare and maintain such by hand ).

Sincerely
Rolf

**Comment by michitux** [comment]
The [count](https://www.dokuwiki.org/plugin:tag#count) syntax is maybe what @chimeric  was referring to.
