### ISSUE TITLE
Wiki crash after installing the plugin

### ISSUE THREAD

**Issue by otx** [dokufreaks/plugin-tag#88]
I have a Debian server with dokuwiki package version 0.0.20091225c-10+squeeze2 install in it, PHP 5.3.3 and Apache2 2.2.16 too visualized with Firefox 21.0 and Opera 12.15. When I install the plugin the entire wiki crash, with symptoms very similar to this:

http://www.freelists.org/post/dokuwiki/Blog-plugin-vs-PHP-524

blank page in all the site and no logs except some "segmentation fault" messages..

If I remove the directory containing the "tag" plugin, the wiki work again...

**Comment by linuxturtle** [comment]
This is also broken in wheezy, dokuwiki version 0.0.20120125b-2+deb7u1

If I try to use the tag plugin, I get this error in /var/log/apache2/error.log:

   PHP Fatal error:  Call to undefined method syntax_plugin_tag_topic::loadHelper() in /srv/var/lib/dokuwiki/lib/plugins/tag/syntax/topic.php on line 82

I'm guessing that tag has been updated to the API for a newer dokuwiki than the one debian packages.

**Comment by linuxturtle** [comment]
Confirmed.  Using the 2010-11-12 source tag fixes the problem with the older version of dokuwiki in debian.

**Comment by LarsGit223** [comment]
As @linuxturtle describes this was an incompatibility between a certain version of the tag plugin and DokuWiki. As the only way to fix it is to use corresponding versions this will be closed now.

@linuxturtle: thanks for your research.
